# Generated by Django 3.1.2 on 2020-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='ester', max_length=50, verbose_name='usuario'),
        ),
    ]
